version: '3.8'
services:
  api:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=production
    volumes:
      - ..:/app
    networks:
      - api-network

networks:
  api-network:
    driver: bridge